#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_X_Tashtit.Resource", IsApplication=true)]

namespace Android_X_Tashtit
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int badge_background = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int calendare = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int cancel = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int lupa = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int ok = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int person = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int persons = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int plus = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int plus_transparent = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int shopping_cart_yellow = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btnBirthDate = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btnCancel = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int btnOk = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int btnSave = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int etBirthDate = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int etCity = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int etClinics = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int etEmail = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int etFamily = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int etName = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int etPassword = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int etPhone = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int etSideEffect = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int etTz = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int fabAdd = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int fabAddClinics = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int fabAddSE = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int fabAddUser = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int imgUser = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int llData = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int lvCities = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int lvClinics = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int lvSideEffects = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int maBtnLogin = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int maCbRemeberMe = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int maEtEmail = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int maEtPassword = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int maLlLogin = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int maLyEmail = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int maLyPassword = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int maTvForgotPassword = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int maTvRegister = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int mnuCities = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int mnuClinics = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int mnuExit = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int mnuLogout = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int mnuMusicPlay = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int mnuMusicStop = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int mnuUsers = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int mnuVaccineUser = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int rvUsers = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int spnClinic = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int spnUserType = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int txtAge = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int txtClinicsName = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int txtEmail = 2130903085;
			
			// aapt resource value: 0x7F03002E
			public const int txtFullName = 2130903086;
			
			// aapt resource value: 0x7F03002F
			public const int txtHeader = 2130903087;
			
			// aapt resource value: 0x7F030030
			public const int txtHeaderClinics = 2130903088;
			
			// aapt resource value: 0x7F030031
			public const int txtName = 2130903089;
			
			// aapt resource value: 0x7F030032
			public const int txtSideEffectName = 2130903090;
			
			// aapt resource value: 0x7F030033
			public const int txtSideEffects = 2130903091;
			
			// aapt resource value: 0x7F030034
			public const int uvBtnLoad = 2130903092;
			
			// aapt resource value: 0x7F030035
			public const int uvEtTz = 2130903093;
			
			// aapt resource value: 0x7F030036
			public const int uvTvDate1 = 2130903094;
			
			// aapt resource value: 0x7F030037
			public const int uvTvDate2 = 2130903095;
			
			// aapt resource value: 0x7F030038
			public const int uvTvDate3 = 2130903096;
			
			// aapt resource value: 0x7F030039
			public const int uvTvName = 2130903097;
			
			// aapt resource value: 0x7F03003A
			public const int uvTvWeeks1 = 2130903098;
			
			// aapt resource value: 0x7F03003B
			public const int uvTvWeeks2 = 2130903099;
			
			// aapt resource value: 0x7F03003C
			public const int uvTvWeeks3 = 2130903100;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040004
			public const int activity_main = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int cities_layout = 2130968581;
			
			// aapt resource value: 0x7F040000
			public const int Clinics = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int SideEffects = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int SingleClinic = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int SingleSideEffects = 2130968579;
			
			// aapt resource value: 0x7F040006
			public const int single_city_layout = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int single_user_layout = 2130968583;
			
			// aapt resource value: 0x7F04000A
			public const int users_layout = 2130968586;
			
			// aapt resource value: 0x7F040008
			public const int user_layout = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int user_vaccine_layout = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int menu_main = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int ic_launcher = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ic_launcher_foreground = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ic_launcher_round = 2131099650;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F070000
			public const int ambient_music = 2131165184;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int action_settings = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int prompt_clinic = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int prompt_usertype = 2131230723;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
